export default {
all_widgets: [
    {
        name: "Clock",
        type: "clock",
        w: 2,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Simple digital clock widget",
        icon: "./img/Clock.png",
        limit: "free,lite,pro",
    },
    {
        name: "Analog clock",
        type: "analogclock",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "Analog clock widget",
        icon: "./img/AnalogClock.png",
        limit: "lite,pro",
    },
    {
        name: "PanelLink",
        type: "panellink",
        w: 2,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Link to panel",
        icon: "./img/PanelLink.png",
        debug: false,
        limit: "free,lite,pro",
    },
    {
        name: "Test",
        type: "test",
        w: 1,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Test widget",
        debug: true,
        limit: "",
    },
    {
        name: "Gauge",
        type: "gauge",
        w: 2,
        h: 2,
        mw: 1,
        mh: 1,
        options: { colors:[]},
        info: "Gauge widget",
        icon: "./img/Gauge.png",
        limit: "lite,pro",
    },
    {
        name: "Relay",
        type: "relay",
        w: 3,
        h: 1,
        mw: 3,
        mh: 1,
        info: "Switch relay widget",
        icon: "./img/Relay.png",
        limit: "free,lite,pro",
    },
    {
        name: "Dimmer",
        type: "dimmer",
        w: 3,
        h: 2,
        mw: 2,
        mh: 2,
        info: "Dimmer widget with state",
        icon: "./img/Dimmer.png",
        limit: "free,lite,pro",
    },
    {
        name: "Select",
        type: "select",
        w: 3,
        h: 1,
        mw: 3,
        mh: 1,
        info: "Select widget",
        icon: "./img/Select.png",
        limit: "free,lite,pro",
        options: { items:[]},
        debug: false,
    },
    {
        name: "Text",
        type: "text",
        w: 2,
        h: 1,
        mw: 1,
        mh: 1,
        info: "View text value",
        icon: "./img/Text.png",
        limit: "free,lite,pro",
    },
    {
        name: "IFrame",
        type: "iframe",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "IFrame block",
        icon: "./img/IFrame.png",
        limit: "lite,pro",
    },
    {
        name: "Value",
        type: "value",
        w: 2,
        h: 1,
        mw: 1,
        mh: 1,
        info: "View value object",
        icon: "./img/Value.png",
        limit: "free,lite,pro",
    },
    {
        name: "Image",
        type: "image",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "View image, MJPEG",
        icon: "./img/Image.png",
        limit: "lite,pro",
    },
    {
        name: "Button",
        type: "button",
        w: 1,
        h: 1,
        mw: 1,
        mh: 1,
        info: "Button for exec method, script",
        icon: "./img/Button.png",
        limit: "free,lite,pro",
    },
    {
        name: "Status",
        type: "status",
        w: 1,
        h: 1,
        mw: 1,
        mh: 1,
        options: { statuses:[]},
        info: "View status",
        icon: "./img/Status.png",
        limit: "pro",
    },
    {
        name: "Send text",
        type: "send_text",
        w: 4,
        h: 1,
        mw: 3,
        mh: 1,
        info: "Send text",
        icon: "./img/SendText.png",
        limit: "lite,pro",
    },
    {
        name: "Slider",
        type: "slider",
        w: 3,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Slider widget",
        icon: "./img/Dimmer.png",
        limit: "lite,pro",
    },
    {
        name: "RoundSlider",
        type: "roundslider",
        w: 3,
        h: 3,
        mw: 2,
        mh: 1,
        options: { color:"#ff0000"},
        info: "Round slider widget",
        icon: "./img/Dimmer.png",
        limit: "pro",
        debug: true
    },
    {
        name: "Time picker",
        type: "timepicker",
        w: 3,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Time picker widget",
        icon: "./img/Timepicker.png",
        limit: "lite,pro",
        debug: false
    },
    {
        name: "Date picker",
        type: "datepicker",
        w: 3,
        h: 1,
        mw: 2,
        mh: 1,
        info: "Date picker widget",
        icon: "./img/Datepicker.png",
        limit: "lite,pro",
        debug: false
    },
    {
        name: "RGB",
        type: "rgb",
        w: 3,
        h: 2,
        mw: 2,
        mh: 2,
        info: "RGB widget with state",
        icon: "./img/RGB.png",
        limit: "lite,pro",
    },
    {
        name: "Graph",
        type: "graph",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "Graph",
        icon: "./img/Graph.png",
        limit: "pro",
        debug: false
    },
    {
        name: "BarGraph",
        type: "bar_graph",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "Bar graph",
        icon: "./img/Graph.png",
        limit: "pro",
        debug: false
    },
    {
        name: "Timeline",
        type: "timeline",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "View history",
        icon: "./img/Timeline.png",
        limit: "pro",
        debug: false
    },
    {
        name: "Map",
        type: "map",
        w: 3,
        h: 3,
        mw: 1,
        mh: 1,
        info: "Map widget",
        icon: "./img/Map.png",
        options:{provider:0},
        limit: "pro",
        debug: false
    },
    {
        name: "Weather",
        type: "weather",
        w: 4,
        h: 9,
        mw: 4,
        mh: 9,
        info: "Weather widget",
        icon: "./img/Weather.png",
        limit: "pro",
        debug: true
    },
    {
        name: "Group",
        type: "group",
        w: 4,
        h: 1,
        mw: 1,
        mh: 1,
        options: { items:[]},
        info: "Group widget",
        icon: "./img/Group.png",
        limit: "pro",
        debug: false
    },
    {
        name: "ProgressBar",
        type: "progressbar",
        w: 4,
        h: 1,
        mw: 1,
        mh: 1,
        info: "Progress widget",
        icon: "./img/Progress.png",
        limit: "lite,pro",
        debug: false
    },
    {
        name: "Table",
        type: "table",
        w: 4,
        h: 4,
        mw: 4,
        mh: 4,
        options: { headers:[]},
        info: "Table widget",
        icon: "./img/Table.png",
        limit: "pro",
        debug: false
    },
]
}